services:
    security.acl.permission.map:
          class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

    admin.post:
        class: BlogBundle\Admin\PostAdmin
        arguments: [~, BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Articles, group: "Articles" }

    admin.postCategory:
        class: BlogBundle\Admin\PostCategoryAdmin
        arguments: [~, BlogBundle\Entity\PostCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Catégories, group: "Articles" }

    admin.comment:
        class: BlogBundle\Admin\CommentAdmin
        arguments: [~, BlogBundle\Entity\Comment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentaires, group: "Articles" }